workflow:
  rules:
    - if: $CI_COMMIT_BRANCH

deploy-pages:
  stage: deploy
  script: /bin/true
  pages: true
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
  environment: production
